
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: crossplane-system
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVFIUktMWVNRTUEyWElWNkwKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gditrN2t6V1lNd3RvYmRDeVRsYVpyaVR4enV6WlpWYkxHUE0xQVdrZQo=
