apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCKa5E/5GqzvuFJqLspvJI1TQ36dzgf5VrseYDoDvPtvLEv3xjGnebPKNhmPDrIUl2hJaFecaN3eboqbq/iCvnyiH7JXpYVxp5tH0tbxuLUdkBUDRvexokBlz7Fc/qe+BIDoE5BezNINQ8Ac8QTf62iOGlbD4NSGjwm0fxD3+SoRF+oz0qRKTed3grYDmWAsaYn3fNwZoF3TgXOeNBBlCDl0CcxXjfJrds2f12Ffhk7wVQ0/x27sWEB6tMAFmX9JwqtxJKRT18kZZog9HyCyeki0Uk4VW4dBe3aWK8pLwwF6shazJI0HdR9HD2i4mJNg9UmQLm8eESaxtg8Kwa7FIsB0VotNWG8kbALZtOSPp5FY502Dvtg4Yk/IqR0YtGWiSpdxQgrfjNaeGON9ChdeGNeRktA+xibWlhcWWW4hJ1MrN1KsckqcZ4/c224Jm4WxNO5r0ZEt6ccKSgO55QwDIK60aO4ysYlRWkGkSTxgiD1dvAxREZN+ZOASKwP62xMNzwqyEibG9cCBUMpomN/YlmRaDF77RQRex/H7Vn/Te3Myc1AvF1KOv6smme9hP4ZxXVNJdeihbAC+Glgs3RCC20MopS4+TfT9/ZaWU/ND5JwgUxwhYUk6qSvj4CKUGBVf2EmkYEWJsWzeIpp6bgN4ENM3OiVdhjXOkeWWUJMO/Z5KGiIslkKq36wcjsiYEwvVYsTsovj53faeYnnaycL8zHrfdVzxhRVVMXF71McM2rP2onC6F6hmh8Hww8CWiIhtp1dkRHR3zXCxqcMdMs3B0g79GhAcc2Hhuw6wY6giOKJqJuTH3zKkLQvRhk5F3jcXUaNoBvrwcH+BkxTyMnglkFRHu6QEw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

