apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: crossplane-configuration-package
  namespace: flux-system
spec:
  interval: 30s
  path: ./deploy/crossplane-composition
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
#  validation: client