---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgB8Yjjr5aEC7P4xPtyo7SQ8wWVxHXEkKfZt7pI1Pa7inbLS110kzuAhhuT0a2R8Q4b2Hn5Ue/ex0/y49KmSBvd4YhgBznOxNM9CN7LxKzClO6yZR1+OfgtyPJo4FsQNtg5Ge0qvpIPdOsZo0eUB2RqIQuOVVti4FGCdAT44SNnJAioHwQ9cl2BjEEjStGKnlOhsNYvMAtcHT52r7hjct9E/Tvj1HoXhCqO9IAiSLYuUOs76vKZUZ0Mg/9uA8n1Evhn2zRg5NNN08R9dAhIMiyOa7NAcodnLevwgmtsEkSUd7x04wvvaise9FYlBxKzLaiNNApRxbCu8vYTb3y+FHmwAb2zJRPM86noKLEjCmAteux/wZiSOVhLxP00a2LkBvktK5Kq3FJc1ke06Qc/8tPzikCoqeuT+iNps1MR5RR1WT4PwhFCCz/KhU74VkmlfvxeOwlh5yj1SE7TCRdCC2tmL6xtxZ+M+Anfgv2xwuYHUtQ2n4/g89H08sa00JwegthnwOBfPuhRBvsu+YMb9Omow7hROP4xgey06eRFYLX0k7q0OjT01D8TVbg8zC/b+FqNoGajHom6diudTzN3aO51kOvazRmOeVIxE4wopEcpGavgFr1zr/RgCJa6O0ph5gpWW7mxbf1dskkLk1nB6inn8CC+4n3rRN3h2MbED5AknAU7iVnSV0fLrZGSNzdSZvgCsPmeKKgiXZmLiyk80lV6V0YOM/IRLA6h3KNUqD6ZsIWY9k7Per4HwdsAjeIFCE1HYrOrJLH/atsS7VRQg7XPKlJdH3qbYM5NIeIu17pBjP7hhhWsIxzmLM5lEgeP9GXyNRx/Dhmq/AT16iIYbcef6H4V8bg==
  template:
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system
    type: Opaque
