apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-eks-composition
spec:
  ignoreCrossplaneConstraints: false
  package: public.ecr.aws/a3h8w9f7/nvogt/eks-cluster-composition:3.0.32
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
