---
apiVersion: eks.sarathy.io/v1beta1
kind: EKSCluster
metadata:
  name: crossplane-prod-cluster
#  annotations:
#    argocd.argoproj.io/sync-wave: "200"
#    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  resourceConfig:
    providerConfigName: aws-provider-config
  parameters:
    region: us-east-1
    vpc-name: "crossplane-vpc-only"
    vpc-cidrBlock: "10.20.0.0/16"

    subnet1-public-name: "public-worker-1 "
    subnet1-public-cidrBlock: "10.20.1.0/27"
    subnet1-public-availabilityZone: "us-east-1a"

    subnet2-public-name: "public-worker-2"
    subnet2-public-cidrBlock: "10.20.2.0/27"
    subnet2-public-availabilityZone: "us-east-1b"

    subnet1-private-name: "private-worker-1 "
    subnet1-private-cidrBlock: "10.20.11.0/27"
    subnet1-private-availabilityZone: "us-east-1a"

    subnet2-private-name: "private-worker-2"
    subnet2-private-cidrBlock: "10.20.12.0/27"
    subnet2-private-availabilityZone: "us-east-1b"

    cluster-role: arn:aws:iam::016194978976:role/AmazonEKSClusterRole-KevinOTesting
    workernode-role: arn:aws:iam::016194978976:role/AmazonEKSNodeRole-KevinOTesting

    k8s-version: "1.29"
    workload-type: "non-gpu"
    workers-size: 3

  compositionRef:
    name: amazon-eks-cluster

  writeConnectionSecretToRef:
    namespace: flux-system
    name: crossplane-flux-cluster-connection